In [40]:
import pandas as pd

In [41]:
#read CSV
#df = pd.read_csv("https://raw.githubusercontent.com/Pankaj-Str/Complete-Python-Mastery/refs/heads/main/53%20DataSet/credit_card_transactions.csv")
df = pd.read_csv("https://raw.githubusercontent.com/Pankaj-Str/Complete-Python-Mastery/refs/heads/main/53%20DataSet/credit_card_transactions_large.csv")
df.head()
 
# other method = copy the link from raw data and paste it at the place of the name of that file in the above code

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,1,103,2025-01-01,ATM,BestBuy,Dining,360.10,Credit Card,Pending,San Francisco
1,2,271,2025-01-01,Online,eBay,Travel,357.02,Credit Card,Declined,Chicago
2,3,107,2025-01-01,ATM,Amazon,Entertainment,829.41,Credit Card,Pending,Chicago
3,4,72,2025-01-01,POS,Amazon,Groceries,790.35,Credit Card,Pending,Los Angeles
4,5,189,2025-01-01,ATM,Amazon,Clothing,311.26,Credit Card,Declined,San Francisco

In [42]:
#check size ie. no of rows and columns
print(df.shape)

(1200, 10)

In [43]:
#print only columns name
df.columns.to_list()

['Transaction_ID',
 'Customer_ID',
 'Transaction_Date',
 'Transaction_Type',
 'Merchant',
 'Category',
 'Amount',
 'Payment_Mode',
 'Transaction_Status',
 'Location']

In [44]:
#to check the summary STATISTICS
df.describe(include='all')

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
count,1200.000000,1200.000000,1200,1200,1200,1200,1200.000000,1200,1200,1200
unique,NaN,NaN,50,3,7,7,NaN,2,3,7
top,NaN,NaN,2025-01-01,Online,BestBuy,Groceries,NaN,Credit Card,Declined,Los Angeles
freq,NaN,NaN,24,416,192,192,NaN,607,416,193
mean,600.500000,150.931667,NaN,NaN,NaN,NaN,494.489692,NaN,NaN,NaN
std,346.554469,86.144962,NaN,NaN,NaN,NaN,283.821837,NaN,NaN,NaN
min,1.000000,1.000000,NaN,NaN,NaN,NaN,5.030000,NaN,NaN,NaN
25%,300.750000,78.000000,NaN,NaN,NaN,NaN,243.565000,NaN,NaN,NaN
50%,600.500000,150.500000,NaN,NaN,NaN,NaN,495.090000,NaN,NaN,NaN
75%,900.250000,225.250000,NaN,NaN,NaN,NaN,734.625000,NaN,NaN,NaN
max,1200.000000,300.000000,NaN,NaN,NaN,NaN,999.560000,NaN,NaN,NaN

In [45]:
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [46]:
df.dtypes

Transaction_ID          int64
Customer_ID             int64
Transaction_Date          str
Transaction_Type          str
Merchant                  str
Category                  str
Amount                float64
Payment_Mode              str
Transaction_Status        str
Location                  str
dtype: object

In [47]:
df['Category'] = df['Category'].fillna('unknown')
df['Payment_Mode'] = df['Payment_Mode'].fillna('unknown')
df['Transaction_Status'] = df['Transaction_Status'].fillna('unknown')
df['Location'] = df['Location'].fillna('unknown')

In [48]:
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [49]:
# convert str from  float columns
df['Amount'] = df['Amount'].astype(float)

In [50]:
df['Amount'] = df['Amount'].fillna(df['Amount'].median)
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [51]:
#convert transaction date into datetime format and extract year ,month,day as new columns
print(df.head()) #print 5 rows
print(df.dtypes) #check datatype

df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])
print(df.dtypes) #check datatype

   Transaction_ID  Customer_ID Transaction_Date Transaction_Type Merchant  \
0               1          103       2025-01-01              ATM  BestBuy
1               2          271       2025-01-01           Online     eBay
2               3          107       2025-01-01              ATM   Amazon
3               4           72       2025-01-01              POS   Amazon
4               5          189       2025-01-01              ATM   Amazon

        Category  Amount Payment_Mode Transaction_Status       Location
0         Dining  360.10  Credit Card            Pending  San Francisco
1         Travel  357.02  Credit Card           Declined        Chicago
2  Entertainment  829.41  Credit Card            Pending        Chicago
3      Groceries  790.35  Credit Card            Pending    Los Angeles
4       Clothing  311.26  Credit Card           Declined  San Francisco
Transaction_ID          int64
Customer_ID             int64
Transaction_Date          str
Transaction_Type          str
Merchant                  str
Category                  str
Amount                float64
Payment_Mode              str
Transaction_Status        str
Location                  str
dtype: object
Transaction_ID                 int64
Customer_ID                    int64
Transaction_Date      datetime64[us]
Transaction_Type                 str
Merchant                         str
Category                         str
Amount                       float64
Payment_Mode                     str
Transaction_Status               str
Location                         str
dtype: object

In [52]:
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Date'] = df['Transaction_Date'].dt.day

df.head()
#check info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      1200 non-null   int64
 1   Customer_ID         1200 non-null   int64
 2   Transaction_Date    1200 non-null   datetime64[us]
 3   Transaction_Type    1200 non-null   str
 4   Merchant            1200 non-null   str
 5   Category            1200 non-null   str
 6   Amount              1200 non-null   float64
 7   Payment_Mode        1200 non-null   str
 8   Transaction_Status  1200 non-null   str
 9   Location            1200 non-null   str
 10  Year                1200 non-null   int32
 11  Month               1200 non-null   int32
 12  Date                1200 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(3), int64(2), str(6)
memory usage: 107.9 KB

In [53]:
#retrieve all transactions made in january 2023
jan_2023 = df[(df['Year'] == 2023) & (df['Month'] == 2)]
jan_2023.head()

#create a report
jan_2023.to_csv("feb_2023.csv")

In [54]:
#Find transactions where Amount > 1000 and Transaction_Type is "Online".
high_online_t = df[(df['Amount'] > 1000) & (df['Transaction_Type'] == 'Online')]
print(high_online_t.head())

Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Transaction_Date, Transaction_Type, Merchant, Category, Amount, Payment_Mode, Transaction_Status, Location, Year, Month, Date]
Index: []

In [55]:
#Select only Approved transactions from the dataset.
approved_t = df[(df['Transaction_Status'] == 'Approved')]
print(approved_t.head())
print(approved_t.shape)

    Transaction_ID  Customer_ID Transaction_Date Transaction_Type Merchant  \
8                9          215       2025-01-01              ATM   Costco
11              12          152       2025-01-01              ATM  Expedia
17              18          277       2025-01-01              POS  Expedia
23              24           59       2025-01-01           Online  Walmart
25              26          188       2025-01-02              POS   Amazon

         Category  Amount Payment_Mode Transaction_Status     Location  Year  \
8       Groceries  357.65  Credit Card           Approved  Los Angeles  2025
11  Entertainment  876.94  Credit Card           Approved      Seattle  2025
17  Entertainment  859.52   Debit Card           Approved        Miami  2025
23         Health  612.49   Debit Card           Approved      Houston  2025
25         Health  675.28  Credit Card           Approved      Houston  2025

    Month  Date
8       1     1
11      1     1
17      1     1
23      1     1
25      1     2
(399, 13)

In [56]:
# feature engineering = trick for column selecting
#apply
#lambda
#cut
#bins

In [57]:
#data Manipulation and Feature Engineering
#Create a new column Discounted_Amount, assuming a 5% discount on all transactions above $500
df['Discounted_Amount'] = df['Amount'].apply(lambda x : x * 0.95 if x > 4000 else x)
df[['Amount','Discounted_Amount']].head()

   Amount  Discounted_Amount
0  360.10             360.10
1  357.02             357.02
2  829.41             829.41
3  790.35             790.35
4  311.26             311.26

In [58]:

#Categorize the Transaction_Amount into Low, Medium, and High based on:
#Low: Below $2000
#Medium: Between $2000 - $4000
#High: Above $4000

#Use cut when you need to segment and sort data values into bins. 
# This function is also useful for going from a continuous variable to a categorical variable. 
# For example, cut could convert ages to groups of age ranges. Supports binning into an equal number of bins,
#  or a pre-specified array of bins.

df['Amount_category'] = pd.cut(
    df['Amount'],
    bins=[-float('inf'),2000,4000,float('inf')],
    labels=['low','medium','high']
)
df[['Amount','Amount_category']].tail()

      Amount Amount_category
1195   75.80             low
1196  576.00             low
1197  568.19             low
1198  878.64             low
1199  560.08             low

In [59]:
#Drop the Merchant column if more than 30% of values are missing.
df.isnull().sum()
missing_value = df['Merchant'].isnull().mean()
if missing_value > 0.3:
    df.drop(columns=['Merchant'])

In [60]:
#Aggregation and Insights
#Find the total transaction amount per Category
total_amt_cat = df.groupby('Category')['Amount'].sum().reset_index()
total_amt_cat

        Category    Amount
0       Clothing  90207.10
1         Dining  85015.63
2    Electronics  76672.25
3  Entertainment  78467.94
4      Groceries  90815.72
5         Health  85100.25
6         Travel  87108.74

In [61]:
#Q1 find the avg transaction amount per category

avg_trans_cat = df.groupby('Category')['Amount'].mean().reset_index()
print(avg_trans_cat)

        Category      Amount
0       Clothing  524.459884
1         Dining  503.051065
2    Electronics  459.115269
3  Entertainment  496.632532
4      Groceries  472.998542
5         Health  522.087423
6         Travel  486.641006

In [62]:
#Q2 find the count transaction amount per category

count_amt_cat = df.groupby('Category')['Amount'].count().reset_index()
count_amt_cat

        Category  Amount
0       Clothing     172
1         Dining     169
2    Electronics     167
3  Entertainment     158
4      Groceries     192
5         Health     163
6         Travel     179

In [63]:
#Q3 Determine the number of declined transactions per Payment_Mode.

declined_trans_payment_mode = df[df['Transaction_Status'] == 'Declined'].count()
print(declined_trans_payment_mode['Payment_Mode'])

416

In [64]:
#Q4 Identify the top 5 most frequent merchants based on transaction count.
merchant_count = df['Merchant'].value_counts().head(5).reset_index()
merchant_count.columns = ['Merchant','Amount']
print(merchant_count)

  Merchant  Amount
0  BestBuy     192
1   Target     179
2     eBay     177
3  Expedia     173
4   Amazon     171

In [65]:
#Q5 Find the average transaction amount per Location
avg_trans_loc = df.groupby('Location')['Amount'].mean().reset_index()
avg_trans_loc.head()

      Location      Amount
0      Chicago  511.114686
1      Houston  487.162901
2  Los Angeles  473.424819
3        Miami  460.013101
4     New York  510.001280

In [66]:
#Find customers who made more than 10 transactions in a single day (potential fraud).
df['Date'] = df['Transaction_Date'].dt.date   #made new column
transactions_per_day = df.groupby(['Customer_ID','Date']).size().reset_index(name='Transaction_Count')
potential_fraud_customers = transactions_per_day[transactions_per_day['Transaction_Count'] > 1]
potential_fraud_customers

      Customer_ID        Date  Transaction_Count
50             12  2025-02-18                  2
58             14  2025-01-31                  2
71             17  2025-02-18                  2
91             25  2025-02-01                  2
92             25  2025-02-10                  2
138            38  2025-02-04                  2
187            49  2025-02-11                  2
218            55  2025-02-12                  2
228            58  2025-01-23                  2
248            63  2025-02-10                  2
365            99  2025-01-10                  2
366            99  2025-01-12                  2
371           100  2025-01-17                  2
382           103  2025-01-01                  2
387           104  2025-02-06                  3
388           104  2025-02-08                  2
407           111  2025-02-01                  2
417           113  2025-01-07                  3
440           118  2025-02-03                  2
467           126  2025-01-23                  2
485           130  2025-01-08                  2
538           144  2025-01-09                  2
562           148  2025-01-09                  2
605           157  2025-02-07                  4
634           164  2025-01-24                  2
666           173  2025-01-23                  3
679           177  2025-01-26                  2
688           179  2025-02-06                  2
749           195  2025-01-29                  2
758           198  2025-01-08                  2
793           209  2025-02-14                  2
822           217  2025-01-20                  2
837           220  2025-01-25                  2
871           227  2025-02-17                  2
886           231  2025-01-05                  2
891           233  2025-01-07                  2
953           250  2025-01-17                  2
960           252  2025-01-03                  2
961           252  2025-01-09                  2
971           254  2025-01-10                  2
986           257  2025-02-11                  2
1007          264  2025-01-14                  2
1052          277  2025-01-11                  2
1081          284  2025-01-06                  2
1103          288  2025-02-12                  2
1111          289  2025-02-07                  2

In [67]:
#Find transactions where Amount > $5000 and Transaction_Type is Online (flag as high-risk).

In [68]:
#Suppose you have another dataset (customer_info.csv) containing Customer_ID, Age, Gender, and Account_Status.

customers = pd.read_csv("https://raw.githubusercontent.com/Pankaj-Str/Complete-Python-Mastery/refs/heads/main/53%20DataSet/customer_info_large.csv")

customers.head()

   Customer_ID  Age  Gender Account_Status
0            1   66    Male       Inactive
1            2   53  Female      Suspended
2            3   40  Female      Suspended
3            4   49   Other       Inactive
4            5   27   Other      Suspended

In [70]:
#Merge it with credit_card_transactions.csv using an appropriate join operation.

merged_df = pd.merge(df,customers, on='Customer_ID',how = 'inner')
merged_df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Date,Discounted_Amount,Amount_category,Age,Gender,Account_Status
0,1,103,2025-01-01,ATM,BestBuy,Dining,360.10,Credit Card,Pending,San Francisco,2025,1,2025-01-01,360.10,low,25,Female,Inactive
1,2,271,2025-01-01,Online,eBay,Travel,357.02,Credit Card,Declined,Chicago,2025,1,2025-01-01,357.02,low,24,Female,Suspended
2,3,107,2025-01-01,ATM,Amazon,Entertainment,829.41,Credit Card,Pending,Chicago,2025,1,2025-01-01,829.41,low,58,Male,Suspended
3,4,72,2025-01-01,POS,Amazon,Groceries,790.35,Credit Card,Pending,Los Angeles,2025,1,2025-01-01,790.35,low,41,Other,Suspended
4,5,189,2025-01-01,ATM,Amazon,Clothing,311.26,Credit Card,Declined,San Francisco,2025,1,2025-01-01,311.26,low,20,Other,Inactive